### PR TITLE
Added January 28th's meeting logs

### PR DESCRIPTION
**Pull request by dginovker**
Edit: These logs now include everything since November 5th, 2018.

I noticed logs haven't been up to date recently and remembered seeing someone saying they wanted to have them. I don't have the chat history going way back to last year, but hopefully I can keep up to date moving forwards.

(If anyone wants to send me the logs for the past year or so, that would be great)

### CODE REVIEW

**Comment by SamsungGalaxyPlayer** [comment]
I unfortunately don't have the time to process these right now, but here are all the logs I have from #monero-research-lab:

[#monero-research-lab.chat.zip](https://github.com/monero-project/research-lab/files/2809396/monero-research-lab.chat.zip)

**Comment by dginovker** [comment]
Thanks Justin. If anyone has IRC dumps from April 2018 to November 2018, I can add them to fill the current gap (and if you have anything prior to that as well).

Additionally I think we should change the naming convention being used; the alphanumeric sorting for these files puts them [all over the place](https://github.com/dginovker/research-lab/tree/master/meta/research-meeting-logs), so I would rather convert them to `ResMeetLogs-YYYY-MM-DD.txt` if everyone's OK on that.

**Comment by b-g-goodell** [comment]
Here is my complete logs from #monero-research-lab as of a , or at least
the logs I have presently on this device. I was going to get this done when
I got back from SBC, but this would be very convenient!

**Comment by b-g-goodell** [comment]
Uploaded my logs to my personal [repo](https://github.com/b-g-goodell/research-lab/blob/master/meta/%23monero-research-lab.txt). Tried to do this earlier. :\

**Pull request closed without merging**
